env: development
#env: production
timezone: Asia/Tehran

ignoreArchWarning: true
hostname: "{you-server-ip}"

storage_dir: /storage

database:
  driver: "sqlite"
  path: "data/homepi.db"

allowed_hosts:
  - 127.0.0.1
  - localhost

allowed_headers:
  - Authorization

jwt:
  access_token:
    secret: "super-secure-jwt-access-token"
    expires_at: 240
  refresh_token:
    secret: "super-secure-jwt-refresh-token"
