name: Publish Docker image
on:
  push:
    branches:
      - master
    tags:
      - v*
jobs:
  push_to_registries:

    name: Push Docker image to Dockerhub
    runs-on: ubuntu-latest

    env:      
      DOCKER_IMAGE: homepi/homepi:latest
      DOCKER_TARGET_PLATFORM: linux/arm/v7

    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
    
      - name: Prepare      
        id: prepare      
        run: |        
          echo ::set-output name=docker_platform::${DOCKER_TARGET_PLATFORM}        

      - name: Declare git repo vars
        id: vars
        shell: bash
        run: |
          echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"
            
      - uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          logout: true

      - name: Build and Push to Docker Hub
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          tags: ${DOCKER_IMAGE}
          push: true
