name: Release

on:
  workflow_dispatch:
    inputs:
      tag_name:
        description: 'Tag name for release'
        required: false
        default: develop
  push:
    branches:
      - develop
    tags:
      - v*

jobs:

  goartifacts:
    name: artifacts
    strategy:
      matrix:
        go-version: [1.17.1]
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    outputs:
      version: ${{ steps.build.outputs.version }}
      release: ${{ steps.build.outputs.release }}
    steps:
    - name: Install Go
      uses: actions/setup-go@v2
      with:
        go-version: ${{ matrix.go-version }}
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install go dependencies
      run: go mod tidy

    - name: Build artifacts
      id: build
      run: |
        make build-artifacts
        printf '::set-output name=version::%s\n' "$(./dist/homepi_linux_amd64 version | head -n 3)"
        printf '::set-output name=release::%s\n' "$(./dist/homepi_linux_amd64 version | head -n 1)"
    - name: 'Upload macOS artifact'
      uses: actions/upload-artifact@v2
      with:
        name: homepi_darwin_amd64
        path: ./dist/homepi_darwin_amd64
        retention-days: 1

    - name: 'Upload linux/amd64 artifact'
      uses: actions/upload-artifact@v2
      with:
        name: homepi_linux_amd64
        path: ./dist/homepi_linux_amd64
        retention-days: 1

    - name: 'Upload linux/arm artifact'
      uses: actions/upload-artifact@v2
      with:
        name: homepi_linux_arm
        path: ./dist/homepi_linux_arm
        retention-days: 1

  publish:
    needs: [goartifacts]
    runs-on: ubuntu-20.04
    permissions:
      contents: write
    steps:

      - uses: actions/download-artifact@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - if: github.event_name == 'workflow_dispatch'
        run: echo "TAG_NAME=${{ github.event.inputs.tag_name }}" >> $GITHUB_ENV

      - if: github.event_name == 'schedule'
        run: echo 'TAG_NAME=develop' >> $GITHUB_ENV

      - if: github.event_name == 'push'
        run: |
          TAG_NAME=${{ github.ref }}
          echo "TAG_NAME=${TAG_NAME#refs/*/}" >> $GITHUB_ENV

      - name: Generate Linux-64 SHA256 checksums
        run: |
          sha256sum homepi_linux_amd64/homepi_linux_amd64 > homepi_linux_amd64.sha256sum
          echo "SHA_LINUX_64=$(cat homepi_linux_amd64.sha256sum)" >> $GITHUB_ENV

      - name: Generate macOS SHA256 checksums
        run: |
          sha256sum homepi_darwin_amd64/homepi_darwin_amd64 > homepi_darwin_amd64.sha256sum
          echo "SHA_MACOS=$(cat homepi_darwin_amd64.sha256sum)" >> $GITHUB_ENV

      - name: Generate Linux-ARM SHA256 checksums
        run: |
          sha256sum homepi_linux_arm/homepi_linux_arm > homepi_linux_arm.sha256sum
          echo "SHA_LINUX_ARM_64=$(cat homepi_linux_arm.sha256sum)" >> $GITHUB_ENV

      - if: env.TAG_NAME == 'develop'
        run: echo 'SUBJECT=HomePi development (prerelease) build' >> $GITHUB_ENV

      - if: env.TAG_NAME != 'develop'
        run: echo 'SUBJECT=HomePi release build' >> $GITHUB_ENV

      - uses: meeDamian/github-release@2.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ env.TAG_NAME }}
          name: ${{ needs.goartifacts.outputs.release }}
          prerelease: ${{ env.TAG_NAME == 'develop' }}
          commitish: ${{ github.sha }}
          gzip: false
          allow_override: true
          files: |
            homepi_darwin_amd64:./homepi_darwin_amd64/homepi_darwin_amd64
            homepi_darwin_amd64.sha256sum:./homepi_darwin_amd64.sha256sum
            homepi_linux_amd64:./homepi_linux_amd64/homepi_linux_amd64
            homepi_linux_amd64.sha256sum:./homepi_linux_amd64.sha256sum
            homepi_linux_arm:./homepi_linux_arm/homepi_linux_arm
            homepi_linux_arm.sha256sum:./homepi_linux_arm.sha256sum
          body: |
            ${{ env.SUBJECT }}
            ```
            ${{ needs.goartifacts.outputs.version }}
            ```
            ### macOS (x64)
            1. Download **homepi_darwin_amd64**
            2. Run `./homepi_darwin_amd64`
            ### Linux (x64)
            1. Download **homepi_linux_amd64**
            2. Run `./homepi_linux_amd64`
            ### Linux (ARM)
            1. Download **homepi_linux_arm**
            2. Run `./homepi_linux_arm`
            ## SHA256 Checksums
            ```
            ${{ env.SHA_LINUX_64 }}
            ${{ env.SHA_MACOS }}
            ${{ env.SHA_LINUX_ARM }}
            ```
